@HOST = http://localhost:3000

### 
# 아이템 1페이지 가져오기
GET  {{HOST}}/items?_page=1&_expand=user&_sort=createdAt&_order=desc HTTP/1.1

###
# 태그 전체 가져오기
GET  {{HOST}}/tags HTTP/1.1

### 
# 아이템 한개 가져오기

@itemId = 69370980-696d-4fef-980d-6a57ab809db4
GET {{HOST}}/items/{{itemId}}?_embed=comments&_expand=user HTTP/1.1
